# Generated by Django 4.2.2 on 2025-03-22 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la lista personalizada')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElementList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idLista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiWeb.customlist')),
                ('idVideojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiWeb.videogame')),
            ],
        ),
    ]
