# Generated by Django 4.2.2 on 2025-03-31 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiWeb', '0002_customlist_elementlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isPlayedList', models.BooleanField(default=False)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idVideojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiWeb.videogame')),
            ],
        ),
    ]
