# Generated by Django 4.2.2 on 2025-04-07 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiWeb', '0003_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estrellas', models.DecimalField(decimal_places=1, default=0.5, max_digits=3)),
                ('comentario', models.CharField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idVideojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiWeb.videogame')),
            ],
        ),
    ]
