# Generated by Django 4.2.2 on 2025-04-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiWeb', '0005_alter_rating_comentario_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Aceptado'), (1, 'Rechazado'), (2, 'Pendiente')], default=2),
        ),
    ]
